### ISSUE TITLE
nesting and/or large size issue with binary parser

### ISSUE THREAD

**Issue by animetrics** [animetrics/PlistCpp#1]
Binary parsing test suite fails.  Out of range issue.

**Comment by smilingpoplar** [comment]
I build on OSX (mountain lion, clang), the test failed.
...
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:195: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 248 but was -8070450532247928584
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:195: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 249 but was -8070450532247928583
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:195: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 250 but was -8070450532247928582
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:195: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 251 but was -8070450532247928581
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:195: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 252 but was -8070450532247928580
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:195: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 253 but was -8070450532247928579
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:195: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 254 but was -8070450532247928578
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:195: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 255 but was -8070450532247928577
                            done.
   Checking long dict... 
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:213: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 0 but was -8070450532247928832
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:213: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 1 but was -8070450532247928831
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:213: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 2 but was -8070450532247928830
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:213: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 3 but was -8070450532247928829
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:213: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 4 but was -8070450532247928828
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:213: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 5 but was -8070450532247928827
/Users/smilingpoplar/tmp/PlistCpp/src/plistTests.cpp:213: error: Failure in WRITE_BINARY_TO_BYTE_ARRAY: Expected 6 but was -8070450532247928826
...

**Comment by animetrics** [comment]
Hi,

Thanks for the report.  Please pull the latest update.  It should be fixed now.  

Best,
Marc
