### ISSUE TITLE
writeUnicode missing (binary)

### ISSUE THREAD

**Issue by ghost** [animetrics/PlistCpp#10]
1 - writeUnicode is missing, might be nice to support;

2 - (binary) the imp is not really optimized a lot of unnecessary stack copies, that makes your code slow and greedy.

Best.

**Comment by animetrics** [comment]
On Mon, Apr 21, 2014 at 06:32:50PM -0700, mmw wrote:

> 1 - writeUnicode is missing, might be nice to support;

Yes.  Currently, only read is supported.  We haven't had the need to
add writes and if someone wants to implement it and issue a pull
request, that would be great.

> 2 - (binary) the imp is not really optimized a lot of unnecessary stack copies
> makes your code slow and greedy.

You mean the return by values?  Can you point to some specific examples?
I believe that many of them will be optimized out via RVO by the
compiler.  

Thanks,
Marc

**Comment by ghost** [comment]
Hello, thx for your prompt reply,

`I believe that many of them will be optimized out via RVO by the
compiler.` don't, when you can return by ref, return by ref, reuse standard vectors, don't copy move then reassign.

for unicode:

std::string must be ASCII if 0x50 && len < 15

```
bool isutf8 = isUTF8(str);
if (not isutf8 && len < 15)
    ->0x50
else {
     ->0x60
     size_t len;
     uint16_t * c = UTF8_EXPAND_TO_U16(str, &len);
   ...  
     for (size_t i = 0; i < len ; ++i) {
          buf[i] = SWAP_HOST_TO_BIG(c[i]);
     }
     ...
}
```

 best.

**Comment by animetrics** [comment]
On Tue, Apr 22, 2014 at 11:45:38AM -0700, mmw wrote:

> Hello, thx for your prompt reply,
> 
> "I believe that many of them will be optimized out via RVO by the
> compiler." don't, when you can return by ref, return by ref, reuse standard
> vectors, don't copy move then reassign.

I'm not sure exactly the extent of what you are trying to suggest?  Do
you mean that RVO doesn't apply in these cases or that you shouldn't
rely on it, or both?  If you believe that RVO works--in which case there
is no performance penalty to returning by value--there are plenty of
reasons to favor return by value instead of passing return objects by
reference to your function/methods.  Code is more clear, less error
prone, and you could even argue that it better adheres to encapsulation
because the caller doesn't need to know the required state of the
return parameter to be passed by reference.  

Best,
Marc

**Comment by ghost** [comment]
Hello, 
"I believe that many of them will be optimized out via RVO by the compiler" that's compiler dependent, don't let any compiler try to interpret what you mean, write what you mean, I guess that's the reason I still need to write assembly when compilers "interpret" too much by aliasing and creating unnecessary tmp references and/or emitting  bounds-checking when they should not, why? because a compiler is not a code-synthax-developer-debugger, there are not wish-makers.

"or that you shouldn't rely on it, or both?" thus both.

And to be honest I "timed" your code, I have already a xml-plist driver using pugi, mine is ~6 times faster (in/out), I also "timed" the corefoundation against your binary imp, yours is slower by a factor of ~3 (in/out), in addition: code compiled with LLVM-CLANG which is taking extra-extra-care of the emitted instructions, in comparison to any other available c-compilers today.

" Code is more clear, less error prone" never seen that in 20 years.

Best.

**Comment by animetrics** [comment]
On Tue, Apr 22, 2014 at 01:17:48PM -0700, mmw wrote:

> Hello,
> "I believe that many of them will be optimized out via RVO by the compiler"
> that's compiler dependent, 

Not really.  RVO has been around for over 20 years and I don't think you
can find a compiler under a decade old that doesn't implement it.  

> don't let any compiler try to interpret what you mean, write what you
> mean.

I would tend to agree.  However I believe that utilizing RVO extends the
expressive power of C++.

> " Code is more clear, less error
> prone" never seen that in 20 years.

Never seen what exactly? 

Do you have some examples of plists for which this library is noticeably
sluggish?

Best,
Marc

**Comment by ghost** [comment]
Hello,

----- digression -----------------------------------------------------------------------------------------------------------
`RVO has been around for over 20 years` the way that is implemented is compiler dependent, arch dependent, dlinker dependent, gcc does not do the same RVO process than MSVC, this kind of standard drives the big lines with numerous shadowed areas, I do know that field from the inside. QFD, if you don't get it, I have nothing to add. -- C++ has been around for 16 years, C11 has been around for 3 years.

`Do you have some examples of plists for which this library is noticeably sluggish?`

"Unfortunately, we don't support that file type.  Try again with a PNG, GIF, or JPG."

`Never seen what exactly?` that writing bad code makes  `Code more clear and less error
 prone` it tends to be the opposite. (sic)

`private interface`
![screen shot 2014-04-23 at 11 43 53 am](https://cloud.githubusercontent.com/assets/407382/2781743/45aa1894-cb17-11e3-9b72-eda610406bbd.png)
`public interface`

![screen shot 2014-04-23 at 11 49 57 am](https://cloud.githubusercontent.com/assets/407382/2781809/2f013806-cb18-11e3-845e-96fb75e04fbe.png)

A big picture maybe you would tend to agree 8-).

![screen shot 2014-04-23 at 12 36 02 pm](https://cloud.githubusercontent.com/assets/407382/2782379/f0654c48-cb1e-11e3-85cb-fdad4a269303.png)

----- end digression -----------------------------------------------------------------------------------------------------------

----- topic -----------------------------------------------------------------------------------------------------------
BTW: unicode writing support would be nice to add, at least would make your imp complete, despite the various performance issues, we discussed. 

Anyway, your actual rule about length and strings is wrong even for 7 and 8, therefor unicode, you already convert u16 to 8 in the reader, you have the necessary tools to do exactly the same, if the conversion fails to ASCII: (boost has an unicode-driver outside the local namespace, use it, for ref,  have a look at the filesystem API)

http://opensource.apple.com/source/CF/CF-855.11/CFBinaryPList.c

```
static void _appendString(__CFBinaryPlistWriteBuffer *buf, CFStringRef str) {
    CFIndex ret, count = CFStringGetLength(str);
    CFIndex needed, idx2;
    uint8_t *bytes, buffer[1024];
    bytes = (count <= 1024) ? buffer : (uint8_t *)CFAllocatorAllocate(kCFAllocatorSystemDefault, count, 0);
    // presumption, believed to be true, is that ASCII encoding may need
    // less bytes, but will not need greater, than the # of unichars
    ret = CFStringGetBytes(str, CFRangeMake(0, count), kCFStringEncodingASCII, 0, false, bytes, count, &needed);
    if (ret == count) {
        uint8_t marker = (uint8_t)(kCFBinaryPlistMarkerASCIIString | (needed < 15 ? needed : 0xf));
        bufferWrite(buf, &marker, 1);
        if (15 <= needed) {
        _appendInt(buf, (uint64_t)needed);
        }
        bufferWrite(buf, bytes, needed);
    } else {
        UniChar *chars;
        uint8_t marker = (uint8_t)(kCFBinaryPlistMarkerUnicode16String | (count < 15 ? count : 0xf));
        bufferWrite(buf, &marker, 1);
        if (15 <= count) {
        _appendInt(buf, (uint64_t)count);
        }
        chars = (UniChar *)CFAllocatorAllocate(kCFAllocatorSystemDefault, count * sizeof(UniChar), 0);
        CFStringGetCharacters(str, CFRangeMake(0, count), chars);
        for (idx2 = 0; idx2 < count; idx2++) {
        chars[idx2] = CFSwapInt16HostToBig(chars[idx2]);
        }
        bufferWrite(buf, (uint8_t *)chars, count * sizeof(UniChar));
        CFAllocatorDeallocate(kCFAllocatorSystemDefault, chars);
    }
    if (bytes != buffer) CFAllocatorDeallocate(kCFAllocatorSystemDefault, bytes);
}
```

----- end topic -----------------------------------------------------------------------------------------------------------
Best.
