### ISSUE TITLE
Public typedefs (Enhancement)

### ISSUE THREAD

**Issue by LiraNuna** [animetrics/PlistCpp#2]
C++ types are long and hard to type (even with a good IDE).
Why not help the programmer and add some types that are extremely useful when handling plists?

Inside of the publicly facing `Plist` class, I would add those types:

```
    typedef std::vector<char> ByteArray;
    typedef std::vector<boost::any> Array;
    typedef std::map<std::string, boost::any> Dictionary;
```

**Comment by animetrics** [comment]
Hi Liran,

Sure.  The usual way to make these suggestions is to fork the repo, make
the mods, issue a pull request.

Thanks,
Marc
