### ISSUE TITLE
crash (This type is not supported)

### ISSUE THREAD

**Issue by haohaodlam** [animetrics/PlistCpp#5]
get crash (This type is not supported) in Binary format file which include string is Chinese characters

**Comment by animetrics** [comment]
Thanks.  This shouldn't be a crash unless you aren't catching
exceptions.  0x60 is the "set" datatype.  I'm not sure why we don't
support it, I will add to the todo list.

Marc

**Comment by haohaodlam** [comment]
The attachment is the file in question, because the string contains Chinese characters, which leads to this problem.

From: animetrics
Date: 2012-11-13 00:26
To: animetrics/PlistCpp
CC: haohaodlam
Subject: Re: [PlistCpp] crash (This type is not supported) (#5)
Thanks. This shouldn't be a crash unless you aren't catching
exceptions. 0x60 is the "set" datatype. I'm not sure why we don't
support it, I will add to the todo list.

Marc

**Comment by animetrics** [comment]
Commit 243840a69 fixes this issue.
