### ISSUE TITLE
get catch and don't not supporte unicode string

### ISSUE THREAD

**Issue by haohaodlam** [animetrics/PlistCpp#7]
issue 1
you modify parseBinaryString() code

```
if(charCount)
{
    std::vector<unsigned char> characterBytes = getRange(d._objectTable, charStartPosition, charCount);
    std::string buffer = std::string((char*) vecData(characterBytes), characterBytes.size()); 
    return buffer;
}
else
{
    std::string buffer = std::string(""); 
    return buffer;
}
```

modify to

```
    std::vector<unsigned char> characterBytes = getRange(d._objectTable, charStartPosition, charCount);
    std::string buffer = std::string((char*) vecData(characterBytes), characterBytes.size()); 
    return buffer;
```

it get catch "Plist::vecData trying to get pointer to empty std::vector"

issue 2
in fun parseBinary()

get a unkown type 0x60 this is unicode string
lib is not supported  unicode string

**Comment by animetrics** [comment]
Hi,

Thanks for the issues.  Can you please post some plists to manifest the above issues.  I believe both have come up in the past.

Thanks,
Marc

**Comment by haohaodlam** [comment]
![itunesmetadata](https://f.cloud.github.com/assets/2775172/2406456/9bab8b24-aa6f-11e3-9c13-cedc4f725e52.jpg)
change,jpg to plist issues file

**Comment by animetrics** [comment]
With the latest version (that has the pull request mergeD), I do not
have any problems reading the plist using PlistCpp. 

Marc

**Comment by animetrics** [comment]
I believe that commit 243840a69 fixes this issue and I haven't heard otherwise so closing it.
